options:
  ppa:
    type: string
    default: ''
    description: |
      PPA to added before installing MAAS. This needs to be set before during
      deployment. Changing after initial deployment has no affect.
  dbname:
    type: string
    default: maas
    description: Name of the database to use when related to PostgreSQL.
  maas-url:
    type: string
    default: ''
    description: |
      URL that rack controllers connect get RPC information and deploying
      machines use for metadata, APT proxy, and DNS.
      .
      It is recommended to leave this unset. In a multi unit deployment the
      maas_url in the regiond.conf will be set to the leader unit for the
      service unless this is set to override that value.
  vip:
    type: string
    default: ''
    description: |
      IP address deploying machines will use to access their metadata,
      proxy, and DNS. (Recommended in multi unit deployments; overrides the
      maas-url config.)
      .
      The virtual IP address will be placed on the primary maas-region unit for
      deploying machines to communicate to for metadata, APT proxy, and DNS.
      .
      For metadata and APT proxy this will be the load balancer on the
      maas-region unit balancing the requests to all active maas-region units.
      DNS will only be resolved the primary maas-region unit.
      .
      Keepalived is used to keep the virtual IP address on the primary unit.
  admin-username:
    type: string
    default: admin
    description: Username for the initial admin user.
  admin-email:
    type: string
    default: noreply@maas
    description: Email for the initial admin user.
  admin-password:
    type: string
    default: ''
    description: |
      Password for the initial admin user. If not set admin user will not be
      created.
  maas-name:
    type: string
    default: juju-maas
    description: Name to identify this MAAS deployment.
  main-archive:
    type: string
    default: http://archive.ubuntu.com/ubuntu
    description: |
      Ubuntu archive used by machines to retrieve packages for Intel
      architectures.
  ports-archive:
    type: string
    default: http://ports.ubuntu.com/ubuntu-ports
    description: |
      Ubuntu archive used by machines to retrieve packages for non-Intel
      architectures.
  enable-http-proxy:
    type: boolean
    default: True
    description: |
      Enable the use of an APT and HTTP/HTTPS proxy.
      .
      Provision machines to use the built-in HTTP proxy (or user specified
      proxy) for APT. MAAS also uses the proxy for downloading boot images.
  http-proxy:
    type: string
    default: ''
    description: |
      Proxy for APT and HTTP/HTTPS.
      .
      This will be passed onto provisioned machines to use as a proxy for APT
      traffic. MAAS also uses the proxy for downloading boot images. If no
      URL is provided, the built-in MAAS proxy will be used.
  upstream-dns:
    type: string
    default: ''
    description: |
      Upstream DNS used to resolve domains not managed by this MAAS
      (space-separated IP addresses).
  dnssec-validation:
    type: string
    default: auto
    description: |
      Enable DNSSEC validation of upstream zones.
      .
      Only used when MAAS is running its own DNS server. This value is used as
      the value of 'dnssec_validation' in the DNS server config.
  ntp-server:
    type: string
    default: ntp.ubuntu.com
    description: |
      Address of NTP server for machines.
      .
      NTP server address passed to machines via a DHCP response.
  default-storage-layout:
    type: string
    default: flat
    description: |
      Storage layout that is applied to a machine when it is commissioned.
      (Supports: flat, vlm, or bcache).
  enable-disk-erasing-on-release:
    type: boolean
    default: False
    description: |
      Erase machines' disks prior to releasing.
  curtin-verbose:
    type: boolean
    default: False
    description: |
      Turn on curtin verbose logging when a machine is being deployed.
      Installation log for the deployed or failed deployed machine will contain
      detailed log information to aid in bug reporting and development.
  haproxy-stats-enabled:
    type: boolean
    default: False
    description: Enable the stats endpoint on the haproxy.
  haproxy-stats-uri:
    type: string
    default: '/haproxy?stats'
    description: URI for the stats endpoint.
  haproxy-stats-auth:
    type: string
    default: 'ubuntu:ubuntu'
    description: |
      HTTP authentication to access the stats endpoint.
      .
      Accepts a multiple user password combinations. Each user password
      combination should be seperated by a ';'. Example:
      .
        ubuntu:ubuntu;ubuntu1:ubuntu1
      .
      Setting to an empty string will result in no authentication.
  keepalived-router-id:
    type: int
    default: 50
    description: |
      Virtual router ID to use for the keepalived configuration. This needs
      to be unique for the entire network where the deployment exists. (Only
      used when a VIP is set.)
