options:
  maas-url:
    type: string
    default: 'http://localhost:5240/MAAS'
    description: |
      URL that rack controllers connect get RPC information and deploying
      machines use for metadata, APT proxy, and DNS.
      .
      It is recommended to leave this unset. Unless an HA proxy is being
      placed in front of the region controllers and you want the rack
      controllers to communicate through the HA proxy instead of directly
      to each region controller.
